apiVersion: v1
kind: Pod
metadata:
  name: hf-pod
spec:
  containers:
  - name: hf-container
    image: nginx:alpine
    env:
    - name: HUGGINGFACE_HUB_CACHE
      value: /data/hf-cache/huggingface/hub
    volumeMounts:
    - name: hf-cache
      mountPath: /data/hf-cache
  volumes:
  - name: hf-cache
    hostPath:
      path: /data/hf-cache  # Must exist on the Kind node and extra volume
      type: Directory