apiVersion: v1
kind: PersistentVolume
metadata:
  name: hf-cache-pv
spec:
  capacity:
    storage: 10Gi  # Adjust size as needed
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  local:
    path: /data/hf-cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-device-plugin-cluster-worker
          - k8s-device-plugin-cluster-control-plane
# Your Kind node name